version: '3.1'

services:

  mysql-node-complete:
    image: mysql:5.7
    container_name: mysql-node-complete
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=node
      - MYSQL_PASSWORD=node
      - MYSQL_DATABASE=node
      - MYSQL_USER=node
      - TZ=America/Sao_Paulo
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-node-complete
    links:
      - mysql-node-complete:db
    ports:
      - 8080:80
    restart: always